remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "SAFE"
description: "Synthetic Audio Forensics Evaluation Challenge"
layout:
  width: "full" # Options: "narrow", "wide", "full"
# minima:
#   skin: auto
